// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.mifos_x.version,
  hash: env.mifos_x.hash,
  // For connecting to server running elsewhere update the tenant identifier
  zeusPlatformTenantId: 'zeus-colending',
  // For connecting to others servers running elsewhere update the base API URL
  baseApiUrls: 'https://dev.mifos.io,https://demo.mifos.io,https://qa.mifos.io,https://staging.mifos.io,https://mobile.mifos.io,https://demo.fineract.dev,https://localhost:8443',
  // For connecting to server running elsewhere set the base API URL
  //baseApiUrl: window['env']['fineractApiUrl'] || 'https://demo.fineract.dev',
  baseApiUrl: 'http://10.100.10.29:8443',
  allowServerSwitch: env.allow_switching_backend_instance,
  apiProvider: '/lms/api',
  apiVersion: '/v1',
  serverUrl: '',
  oauth: {
    enabled: false,  // For connecting to Mifos X using OAuth2 Authentication change the value to true
    serverUrl: ''
  },
  defaultLanguage: 'en-US',
  supportedLanguages: 'en-US,fr-FR',
  enableLogoutOnUserInActive: true,
  logoutOnUserInActiveAfter: 20, //in minutes
  secret_key:'Rc8qO5nwvY0skeTc',
  IV:'o!6y4q$is5z%^gub',
};

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
console.log("Loading environment.dev.ts - server URL: ", environment.serverUrl);
environment.oauth.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}`;
