// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.mifos_x.version,
  hash: env.mifos_x.hash,
  // For connecting to server running elsewhere update the tenant identifier
  zeusPlatformTenantId: 'zeus-colending',
  // For connecting to others servers running elsewhere update the base API URL
  baseApiUrls: 'https://dev.mifos.io,https://demo.mifos.io,https://qa.mifos.io,https://staging.mifos.io,https://mobile.mifos.io,https://demo.fineract.dev,https://localhost:8443',
  // For connecting to server running elsewhere set the base API URL
  baseApiUrl: 'http://localhost:8443',
  allowServerSwitch: env.allow_switching_backend_instance,
  apiProvider: '/lms/api',
  apiVersion: '/v1',
  serverUrl: '',
  oauth: {
    enabled: true,  // For connecting to Mifos X using OAuth2 Authentication change the value to true
    serverUrl: ''
  },
  defaultLanguage: 'en-US',
  supportedLanguages: 'en-US,fr-FR',
  enableLogoutOnUserInActive: true,
  logoutOnUserInActiveAfter: 20, //in minutes
  secret_key:'fv2IFESZ0GusMZVY',
  IV:'wrxq0zs1!bna3gme',
};

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
environment.oauth.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}`;
